/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class appsecante_JavaCalc */

#ifndef _Included_appsecante_JavaCalc
#define _Included_appsecante_JavaCalc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     appsecante_JavaCalc
 * Method:    calLin
 * Signature: (DDDDD)D
 */
JNIEXPORT jdouble JNICALL Java_appsecante_JavaCalc_calLin
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     appsecante_JavaCalc
 * Method:    calQua
 * Signature: (DDDDDD)D
 */
JNIEXPORT jdouble JNICALL Java_appsecante_JavaCalc_calQua
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
